# Generated by Django 4.0.4 on 2022-06-29 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ramsched', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_artist', models.TextField(blank=True)),
                ('service_client', models.TextField(blank=True)),
                ('service_date', models.TextField(blank=True)),
                ('service_type', models.TextField(blank=True, choices=[('T', 'Tattoo'), ('H', 'Henna'), ('P', 'Piercing')])),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.TextField(blank=True)),
                ('voucher_type', models.TextField(blank=True, choices=[('30', '30 percent'), ('40', '40 percent'), ('50', '50 percent')])),
                ('voucher_date', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clientinformations',
            old_name='newClientName',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='clientinformations',
            old_name='newClientphoneNo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clientinformations',
            old_name='newtimeSession',
            new_name='first',
        ),
        migrations.AddField(
            model_name='clientinformations',
            name='gender',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientinformations',
            name='last',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientinformations',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramsched.service')),
                ('voucers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ramsched.voucher')),
            ],
        ),
    ]
