# Generated by Django 4.0.4 on 2022-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ramsched', '0002_artistinformation_service_voucher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='voucers',
            new_name='payment_voucher',
        ),
    ]
