# Generated by Django 4.0.4 on 2022-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ramsched', '0003_rename_voucers_payment_payment_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(blank=True),
        ),
    ]
