# Generated by Django 4.0.3 on 2022-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.TextField(blank=True)),
                ('CustomerContact', models.TextField(blank=True)),
                ('CustomerAddress', models.TextField(blank=True)),
                ('CustomerGender', models.TextField(blank=True)),
                ('CustomerPackageType', models.TextField(blank=True)),
            ],
        ),
    ]
