# Generated by Django 4.0.3 on 2022-04-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ilano_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='CustomerInformations',
        ),
    ]
