# Generated by Django 4.0.3 on 2022-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(default=True)),
                ('sex', models.TextField(default=True)),
                ('age', models.TextField(default=True)),
                ('email', models.TextField(default=True)),
                ('height', models.TextField(default=True)),
                ('weight', models.TextField(default=True)),
                ('foodallergens', models.TextField(default=True)),
            ],
        ),
    ]
