# Generated by Django 4.0.3 on 2022-04-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Info',
        ),
    ]
