# Generated by Django 4.0.3 on 2022-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisystem', '0002_rename_items_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='foodallergens',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='fullname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='height',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='weight',
            field=models.TextField(blank=True),
        ),
    ]
