# Generated by Django 4.0.4 on 2022-06-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisystem', '0003_alter_info_age_alter_info_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CusFName', models.TextField(blank=True)),
                ('CusLName', models.TextField(blank=True)),
                ('CusBlk', models.TextField(blank=True)),
                ('CusBrgy', models.TextField(blank=True)),
                ('CusMuni', models.TextField(blank=True)),
                ('CusProv', models.TextField(blank=True)),
                ('CusZip', models.TextField(blank=True)),
                ('CusContactNo', models.TextField(blank=True)),
                ('CusEmailAdd', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdName', models.TextField(blank=True)),
                ('ProdDesc', models.TextField(blank=True)),
                ('ProdPrice', models.TextField(blank=True)),
                ('ProdQty', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayDate', models.DateField()),
                ('PayType', models.TextField(blank=True)),
                ('PayAmount', models.TextField(blank=True)),
                ('CusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrAmount', models.TextField(blank=True)),
                ('OrDate', models.DateField()),
                ('OrQty', models.TextField(blank=True)),
                ('OrStatus', models.TextField(blank=True)),
                ('CusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryType', models.TextField(blank=True)),
                ('DeliveryDate', models.DateField()),
                ('ArrivalDate', models.DateField()),
                ('CusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.customer')),
                ('OrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrisystem.order')),
            ],
        ),
    ]
